[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "infra-guard"
version = "0.1.0"
dependencies = []

[project.scripts]
infra-guard = "infra_guard.main:main"

[tool.setuptools.packages.find]
include = ["infra_guard*"]